---
title: "Wastewater import script"
author: "MM"
date: "2024-05-30"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# April 2023: Undercounting COVID Cases
# clear R's brain
dir.create(tempdir()) # solve Error in file(out, "wt") : cannot open the connection
rm( list = ls())
# load libraries
preq = c( "ggpmisc", "gridExtra", "ggfortify", "scales", 
          "readxl", "readr", "stats", "haven", "Matrix", "foreign", "zoo", 
          "prophet", "corrr", "broom", "usethis", "rvest", "forecast", 
          "seasonal", "purrr", "data.table", "fable", "fabletools", "ggplot2", 
          "feasts", "tsibble", "tsibbledata", "tidyverse"
          )
#for (y in preq) install.packages(y, dep = TRUE)
sapply(preq, library, character.only=T)
```

```{r global_variables, echo=TRUE}

#rm( list = ls())
#file_loc <- "C:/Users/mustam23/OneDrive\ -\ Pfizer/Documents/Projects/wastewater/"
file_loc <- paste0(getwd())
data_loc <- paste0(file_loc, "/data_downloads/") # a location for data files 
# check if the string contains "mustam23"
work_laptop <- grepl("mustam23", getwd())
```

```{r import_bigfile, echo=TRUE}
# read the big file
bigfile <- read.csv(paste0(data_loc, "/bigfile.csv"))
    #select all date columns and convert them to date
    selected_columns <- names(bigfile)[grep("start_|end_|date", names(bigfile))]
    bigfile <- bigfile %>% mutate_at(selected_columns, ymd) 
```

#import OWID data
```{r import_owid, echo=TRUE}
# import OWID data
owid <- 
  read.csv(paste0(data_loc, "owid-covid-hospitalizations.csv")) %>%
  mutate(date = ymd(date),
         value = as.numeric(value),
         weekday = weekdays(date)) %>%
  rename(location_name = entity) %>%
  filter(grepl("hospital", indicator))

```

#functions next_saturday, epiweek_to_date
```{r epiweek_to_date_function, echo=TRUE}

next_saturday <- function(date){
  date + 7 - match(weekdays(date), 
                   c("Sunday", "Monday","Tuesday","Wednesday",
                     "Thursday","Friday", "Saturday"))
}

# write a function with a single input year that returns a correction factor of -3 if the year is 2020, 2 if the year is 2021, 1 if the year is 2022, 0 if the year is 2023, -1 if the year is 2024

correction_factor <- function(years) {
  # Force years to be integers
  years <- as.numeric(years)
  # Initialize vector to store results
  factors <- numeric(length(years))
  for (i in seq_along(years)) {
    year <- years[i]
    if (year == 2019){
      factors[i] <- +5
    } else if (year == 2020) {
      factors[i] <- -3
    } else if (year == 2021) {
      factors[i] <- 2
    } else if (year == 2022) {
      factors[i] <- 1
    } else if (year == 2023) {
      factors[i] <- 0
    } else if (year == 2024) {
      factors[i] <- -1
    } else if (year == 2025) {
      factors[i] <- -3
    } else {
      factors[i] <- NA
    }
  }
  return(factors)
}

epiweek_to_date <- function(Year = 2020, Week =1) {
  #force Year and Week to be integers
  Year <- as.integer(Year)
  Week <- as.integer(Week)
  #return the date of the first day of the week
  return(as.Date(paste0(as.character(Year), "-01-01")) + 7 * as.integer(Week) - 1 + correction_factor(Year))
}

```
#date to cdc date function
```{r date_tocdcdate_function, echo=TRUE}
# The function takes a date as input and returns the corresponding CDC datethe closest epiweek. source https://ndc.services.cdc.gov/wp-content/uploads/2021/02/MMWR_Week_overview.pdf
# next_saturday() probably works better here

date_to_cdcdate <- function(date) {
  #force date to be a date
  date <- as.Date(date)
  year = year(date)
  day = as.numeric(date - as.Date(paste0(year, "-01-01")))
  #calculate number of days from the beginning of the year
  week = as.integer(day/7) + 1
  #calculate the week number
  year_week = paste0(year, "-", week) 
  #calculate the year-week
  cdcdate = epiweek_to_date(year, week) 
  diff = cdcdate -date
  #calculate the difference between the date and the epiweek
  week = ifelse(diff > 3, week - 1, week)
  #adjust week number if the difference between the date and the epiweek is greater than 3
  week = ifelse(diff < -3, week + 1, week) 
  #adjust week number if the difference between the date and the epiweek is less than -3
  cdcdate = epiweek_to_date(year, week)
  return(cdcdate)
}
```
#create custom lag and lead functions


###############below is a list of all files we want to import and modify

```{r define_filenames, echo=TRUE}

# <- "Austria 20240304 dl_blverlauf.csv"
ww_aus <- "Austria 20240304 dl_natmon_01.csv"
hosp_aus <- "Austria 20240304 SARI_Wohnregion_Patient_v202307.csv"
cases_can <- "Canada 20240304 covid19-download.csv"
ww_can <- "Canada 20240306 covid19-wastewater.csv"
ww_dk <- "Denmark 2024-02-28_dk_wastewater_data.csv"
cases_den <- "Denmark 20240304 03_confirmed_cases_dead_admitted_sex.csv"
hosp_den <- "Denmark 20240304 06_new_admissions_region_day.csv"
#cases2_den <- "Denmark 20240304 08_confirmed_cases_regions.csv"
ww_fin <- "Finland 20240304 Coronavirus wastewater monitoring weekly report.csv"
hosp_fin <- "Finland 20240304 fact_epirapo_respinfcare.csv"
ww_neth <- "Netherlands_download_weekly_ww.tab"
ww_scot <- "Scotland RNAMonitoring_Public.csv"
ww_swe <- "Sweden 2024 SLU_wastewater_data.csv"
sites_swe <- "Sweden SLU_COVID_collection_sites.xlsx"
ww_usa <- "United States 20240305 wastewater_surveillance_viral_activity_level_over_time_data.csv"
hosp2_usa <- "data_table_for_currently_hospitalized_covid19_patients_-_the_united_states.csv"
hosp_usa <- "data_table_for_weekly_covid19_hospital_admissions_-_the_united_states.csv"
death_usa <- "data_table_for_weekly_deaths__the_united_states.csv"

```
