---
title: "linear regression models, Denmark"
author: "MM"
date: "2024-06-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## function to run regression models is located in the USA script
## result <- run_linear_regression(df, "y", c("x1", "x2", "x3"))
# print(result)
# Assuming 'df' is your dataframe, 'y' is the response variable, and c('x1', 'x2', 'x3') are the predictor variables



# Run regressions on the usa dataset
```{r run_regressions, echo=TRUE}
#Model 1:  hosp = wastewater
#Model 2: hosp = log(ww)
#Model 3: log(hosp) = log(ww)
#Model 4: hosp = lag1(ww)
#Model 5: hosp = lag1(ww) + days2022 + subvariant
#Model 6: hosp = lag1(ww) + subvariant
#Model 7: hosp = lag1(ww) + days2022

den_model1 <- run_linear_regression(den_dataset, "hosp_new", c("viral_load"))
den_model2 <- run_linear_regression(den_dataset, "hosp_new", c("log_viral_load"))
den_model3 <- run_linear_regression(den_dataset, "log_hosp", c("log_viral_load"))
den_model4 <- run_linear_regression(den_dataset, "hosp_new", c("lag1_viral_load"))
den_model5 <- run_linear_regression(den_dataset, "log_hosp", c("viral_load"))
#den_model5 <- run_linear_regression(den_dataset %>% mutate(days2022 = as.numeric(date - min(date))),
#                                    "hosp_new", c("viral_load", "days2022", "subvariant"))
den_model6 <- run_linear_regression(den_dataset, 
                                    "hosp_new", c("viral_load", "subvariant"))
den_model7 <- run_linear_regression(den_dataset %>% mutate(days2022 = as.numeric(date - min(date))),
                                    "hosp_new", c("viral_load", "days2022"))
den_model8 <- run_linear_regression(den_dataset, 
                                    "log_hosp", c("log_viral_load", "subvariant"))
                                    
#den_models <- list(den_model1, den_model2, den_model3)
# Print the results
print(den_model1)
print(den_model2)
print(den_model3)
print(den_model4)
print(den_model5)
print(den_model6)
print(den_model7)
print(den_model8)

print(den_model1$r_squared)
print(den_model2$r_squared)
print(den_model3$r_squared)
print(den_model4$r_squared)
print(den_model5$r_squared)
print(den_model6$r_squared)
print(den_model7$r_squared)
print(den_model8$r_squared)




den_dataset_models <- den_dataset
den_dataset_models$predicted_m1 <- den_model1$predicted_values
den_dataset_models$predicted_m2 <- den_model2$predicted_values
den_dataset_models$predicted_m3 <- 
  den_model3$predicted_values %>% exp() #undo the log transformation

den_dataset_models$predicted_m4 <- den_model4$predicted_values
den_dataset_models$predicted_m5 <- den_model5$predicted_values %>% exp() 
den_dataset_models$predicted_m6 <- den_model6$predicted_values
den_dataset_models$predicted_m7 <- den_model7$predicted_values
den_dataset_models$predicted_m8 <- den_model8$predicted_values %>% exp() 

den_dataset_models$residuals_m1 <- den_model1$residuals
den_dataset_models$residuals_m2 <- den_model2$residuals
den_dataset_models$residuals_m3 <- den_model3$residuals
den_dataset_models$residuals_m4 <- c(NA, den_model4$residuals)
den_dataset_models$residuals_m5 <- den_model5$residuals
den_dataset_models$residuals_m6 <- den_model6$residuals
den_dataset_models$residuals_m7 <- den_model7$residuals
den_dataset_models$residuals_m8 <- den_model8$residuals

den_model1_csv <-
  data.frame(
    den_model1$coefficients %>% t() %>% 
      as.data.frame() %>% 
      rownames_to_column("variable"),
    den_model1$r_squared,
    den_model1$aic,
    den_model1$bic,
    den_model1$mape)

den_model2_csv <-
  data.frame(
    den_model2$coefficients %>% t() %>% 
      as.data.frame() %>% 
      rownames_to_column("variable"),
    den_model2$r_squared,
    den_model2$aic,
    den_model2$bic,
    den_model2$mape)

den_model3_csv <-
  data.frame(
    den_model3$coefficients %>% t() %>% 
      as.data.frame() %>% 
      rownames_to_column("variable"),
    den_model3$r_squared,
    den_model3$aic,
    den_model3$bic,
    den_model3$mape)

den_model4_csv <-
  data.frame(
    den_model4$coefficients %>% t() %>% 
      as.data.frame() %>% 
      rownames_to_column("variable"),
    den_model4$r_squared,
    den_model4$aic,
    den_model4$bic,
    den_model4$mape)

den_model5_csv <-
  data.frame(
    den_model5$coefficients %>% t() %>% 
      as.data.frame() %>% 
      rownames_to_column("variable"),
    den_model5$r_squared,
    den_model5$aic,
    den_model5$bic,
    den_model5$mape)

den_model6_csv <-
  data.frame(
    den_model6$coefficients %>% t() %>% 
      as.data.frame() %>% 
      rownames_to_column("variable"),
    den_model6$r_squared,
    den_model6$aic,
    den_model6$bic,
    den_model6$mape)

den_model7_csv <-
  data.frame(
    den_model7$coefficients %>% t() %>% 
      as.data.frame() %>% 
      rownames_to_column("variable"),
    den_model7$r_squared,
    den_model7$aic,
    den_model7$bic,
    den_model7$mape)
  
  
```

# plot predicted and observed hospitalizations
```{r plot_predicted_observed, echo=TRUE}
# Plot predicted vs observed hospitalizations for Model 5

ggplot(den_dataset_models, aes(x = hosp_new)) +
  geom_point(aes(y=predicted_m6), color = "blue3") +
  #geom_line(aes(y=hosp_new), color = "red2") +
  #geom_point(aes(y=predicted_m1), color = "black") +
  labs(title = "Predicted Model 5 vs Observed Hospitalizations",
       x = "Date",
       y = "Predicted Hospitalizations")



ggplot(den_dataset_models, aes(x = date)) +
  geom_line(aes(y=predicted_m1), color = "blue3") +
  geom_line(aes(y=predicted_m8), color = "red2") +
  geom_line(aes(y=hosp_new), color = "black", linetype=2) +
  #geom_abline(intercept = 0, slope = 1, color = "red") +
  labs(title = "Predicted Model 1 (blue) vs Model 8 (red) vs Observed (dashed) 
       New Covid Hospitalizations, Denmark, 2022-2024",
       x = "Date",
       y = "Predicted Hospitalizations") 





```