---
title: "Correlation analysis"
author: "MM"
date: "2024-05-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

############Rolling correlation###############################################




```{r correlation_functions, echo=TRUE}

library(dplyr)
library(tidyr)
library(purrr)

# Function to calculate correlation and its confidence interval
calc_cor <- function(df) {
  numeric_df <- df %>% select_if(is.numeric)
  
  cor_ci <- function(x, y) {
    r <- cor(x, y, use = "pairwise.complete.obs")
    n <- sum(!is.na(x) & !is.na(y))
    z <- 0.5 * log((1 + r) / (1 - r))
    se <- 1 / sqrt(n - 3)
    z_ci <- z + c(-1.96, 1.96) * se
    r_ci <- (exp(2 * z_ci) - 1) / (exp(2 * z_ci) + 1)
    return(list(r = r, r_ci = r_ci, n = n))
  }
  
  cor_data <- expand.grid(var1 = colnames(numeric_df), var2 = colnames(numeric_df))
  cor_data <- cor_data %>% filter(var1 != var2)
  
  cor_data <- cor_data %>%
    rowwise() %>%
    mutate(
      result = list(cor_ci(numeric_df[[var1]], numeric_df[[var2]])),
      correlation = result$r,
      lower_ci = result$r_ci[1],
      upper_ci = result$r_ci[2],
      n_obs = result$n
    ) %>%
    select(-result) %>%
    ungroup()
  
  return(cor_data)
}

# Function to group by a variable and calculate correlations with confidence intervals and pairwise observations
fxn_correlations <- function(data, group_var) {
  data %>%
    group_by({{ group_var }}) %>%
    nest() %>%
    mutate(correlation = map(data, calc_cor)) %>%
    select({{ group_var }}, correlation) %>%
    unnest(correlation) %>%
    filter({{ group_var }} != "" & !is.na({{ group_var }})) %>%
    ungroup()
}

```

```{r correlation_example, echo=TRUE}
#fxn_correlations(df, group)
cor_usa_variant <- 
  fxn_correlations(usa_dataset %>% filter(variant == "Omicron"), 
                 subvariant) %>% 
    mutate(dataset = "usa by subvariant") %>%
  filter(!is.na(correlation)) #%>%
View(cor_usa_variant)

cor_usa_all <- 
  calc_cor(usa_dataset %>% filter(variant == "Omicron")) %>%
  mutate(dataset = "usa all") %>%
  filter(!is.na(correlation)) #%>%

View(cor_usa_all)
cor_den_variant <- 
  fxn_correlations(den_dataset %>% filter(variant == "Omicron"), 
                 subvariant) %>% 
    mutate(dataset = "den by subvariant") %>%
  filter(!is.na(correlation)) #%>%
View(cor_den_variant)

cor_den_all <- 
  calc_cor(den_dataset %>% filter(variant == "Omicron")) %>%
  mutate(dataset = "den all") %>%
  filter(!is.na(correlation)) #%>%

View(cor_den_all)

cor_neth_variant <- 
  fxn_correlations(neth_dataset %>% filter(variant == "Omicron"), 
                 subvariant) %>% 
    mutate(dataset = "neth by subvariant") %>%
  filter(!is.na(correlation)) #%>%
View(cor_neth_variant)

cor_neth_all <- 
  calc_cor(neth_dataset %>% filter(variant == "Omicron")) %>%
  mutate(dataset = "neth all") %>%
  filter(!is.na(correlation)) #%>%

View(cor_neth_all)


```

```{r correlation_subvariant, echo=TRUE}

# bind correlation dataframes
correlations_df <- 
  bind_rows(cor_usa_variant, cor_usa_all) %>% 
  bind_rows(cor_den_variant, cor_den_all) %>%
  bind_rows(cor_neth_variant, cor_neth_all) %>%
  mutate(variant = "Omicron") %>%
  relocate(variant) #%>%
  
#View(correlations_df)
# save correlations_df as a csv file
write.csv(correlations_df, 
          file = paste0(getwd(), "/output/correlations_95ci_", 
                        paste(format(Sys.time(), "%Y-%m-%d-%I%p")), ".csv"),
          quote = TRUE,
          na = "",
          row.names = FALSE)

```

```{r correlation_example, echo=TRUE}

```

```{r correlation_subvariant, echo=TRUE}

# Calculate correlation matrices by group in R using the tidyverse package


# Combine correlation matrices into a single data frame
dataframes <- list(
  usa_variant_cor = usa_variant_cor,
  usa_subvariant_cor = usa_subvariant_cor,
  neth_variant_cor = neth_variant_cor,
  neth_subvariant_cor = neth_subvariant_cor,
  den_variant_cor = den_variant_cor,
  den_subvariant_cor = den_subvariant_cor
)

lapply(names(dataframes), function(name) {
  write.csv(dataframes[[name]], 
            file = paste0(getwd(), "/output/leadlag/" ,paste0(name), "_",
                          paste(format(Sys.time(), "%Y-%m-%d-%I%p")), ".csv"),
            quote = TRUE,
            na = "",
            row.names = FALSE)
})

```

